version: 1.0.{build}
image: Visual Studio 2022
before_build:
- ps: nuget restore BuildUploader.sln
build:
  verbosity: minimal
after_build:
- cmd: 7z a UnityCloudBuildSteamUploader.zip "%APPVEYOR_BUILD_FOLDER%\UnityCloudBuildSteamUploader\*"
artifacts:
- path: UnityCloudBuildSteamUploader.zip
  name: UnityCloudBuildSteamUploader.zip